[general]
static=yes
writeprotect=no

[from-internal]
exten => _X.,1,NoOp(Outbound Call from Softphone)
 same => n,Stasis(crm-dialer,outbound,${EXTEN})
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Inbound Call Received on DID: ${EXTEN})
 same => n,Answer()
 same => n,Stasis(crm-dialer,inbound,${EXTEN})
 same => n,Hangup()