[general]
type=global
user_agent=Asterisk PBX

; --- UDP Transport ---
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; --- Telecaller Softphone 1001 ---
[1001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=auth1001
aors=1001
direct_media=no

[auth1001]
type=auth
auth_type=userpass
password=SecretPassword1001
username=1001

[1001]
type=aor
max_contacts=2
remove_existing=yes