[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[endpoint-basic](!)
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw

[auth-userpass](!)
type=auth
auth_type=userpass

[aor-single-reg](!)
type=aor
max_contacts=1

; Agent 1001 softphone credentials
[1001](endpoint-basic)
auth=1001-auth
aors=1001

[1001-auth](auth-userpass)
username=1001
password=SecretPassword1001

[1001](aor-single-reg)